### ISSUE TITLE
apko.alpine(): argument "branch" has default value but is not optional

### ISSUE THREAD

**Issue by shykes** [vito/daggerverse#2]
## Problem

When calling `apko.alpine()`, the `edge` argument has a default value, but is not optional. This makes its default value useless.

I was going to fix it, but have no idea how to do this in Bass. It might be a bug in the Bass SDK (just a guess).

**Comment by vito** [comment]
Closing as the fix for this will actually be upstream; the Bass SDK is already doing what will become the "right thing" - https://github.com/dagger/dagger/issues/6749#issuecomment-2078334724
